name:                network-haskell-battleship
version:             0.1.0.0
github:              "matheusja/network-haskell-battleship"
license:             BSD3
author:              "matheus da silva jahnke"
maintainer:          "matheusjahnke@hotmail.com"
copyright:           "matheusja"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/matheusja/network-haskell-battleship#readme>

dependencies:
- base >= 4.7 && < 5
- network
- text
- bytestring
- containers
- ansi-terminal

library:
  source-dirs: src

executables:
  server:
    main:                Main.hs
    source-dirs:         server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - network-haskell-battleship
  client:
    main:                Main.hs
    source-dirs:         client
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - network-haskell-battleship
